pagure: ensure files is list and not a dict_keys
This fixes an issue with project defining a Zuul job config that
use a file matcher:

2020-06-01 12:18:35,833 ERROR zuul.Pipeline.fedora.check: Error freezing job graph for <QueueItem 0x7f7e8e465438 for <Change 0x7f7ea0c8f748 project: fedora-infra/ansible number: 100 patchset: cb7ab828c28754fe0a4d02f0d5c0aecf7921e016 updated: 1591013908 status: failure state: open> in check>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/zuul/manager/__init__.py", line 798, in prepareItem
    item.freezeJobGraph()
  File "/usr/lib/python3.6/site-packages/zuul/model.py", line 2208, in freezeJobGraph
    self, ppc, skip_file_matcher)
  File "/usr/lib/python3.6/site-packages/zuul/model.py", line 4190, in createJobGraph
    self._createJobGraph(item, ppc, ret, skip_file_matcher)
  File "/usr/lib/python3.6/site-packages/zuul/model.py", line 4145, in _createJobGraph
    not frozen_job.changeMatchesFiles(change):
  File "/usr/lib/python3.6/site-packages/zuul/model.py", line 1678, in changeMatchesFiles
    if self.file_matcher and not self.file_matcher.matches(change):
  File "/usr/lib/python3.6/site-packages/zuul/change_matcher.py", line 149, in matches
    if len(change.files) == 1 and self.commit_regex.match(change.files[0]):
TypeError: 'dict_keys' object does not support indexing

Change-Id: I40f503b1e3d9629472c759911b15b718e6c79cff